version: "3"
services:
  mysql:
    build: ./src/mysql
    container_name: mysql_zenn
    image: mysql:5.7
    ports:
      - ${MYSQL_PORTS}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./src/mysql/my.cnf:/tmp/src/mysql/my.cnf
    tty: true
    networks:
      python_network:
        ipv4_address: ${IPV4}

  metabase:
    container_name: metabase_zenn
    image: metabase/metabase
    ports:
      - ${METABASE_PORTS}
    links:
      - mysql
    networks:
      - python_network
    depends_on:
      - mysql
      # python-app:
      #   condition: service_completed_successfully

  python-app:
    restart: on-failure
    build: .
    volumes:
      - ./src/python/:/tmp/src/python
    working_dir: /tmp/src/python
    container_name: python3-practice
    image: python3
    links:
      - mysql
    networks:
      - python_network
    depends_on:
      - metabase

networks:
  python_network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: ${SUBNET}
         gateway: ${GATEWAY}
