version: "3"
services:
  python-app:
    build: .
    volumes:
      - ./src/python/:/tmp/src/python
    working_dir: /tmp/src/python
    ports:
      - 8888:8888
    container_name: python3-practice
    tty: true
